AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: true

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.2.0/24"

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref MyInternetGateway

  AssociatePublicSubnetRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: <your-nat-gateway-id>  # Add your NAT Gateway ID here

  AssociatePrivateSubnetRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <your-ami-id>  # Add your AMI ID here
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet

  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <your-ami-id>  # Add your AMI ID here
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet

  MyInstance3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <your-ami-id>  # Add your AMI ID here
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnet

  MyInstance4:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <your-ami-id>  # Add your AMI ID here
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnet
