Resources:
  Mini-Network-VPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/24
    EnableDnsSupport: 'true'
    EnableDnsHostnames: 'true'
    Tags:
     - Key: Name
       Value: Mini-Network

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: chandan	
      ImageId: ami-0287a05f0ef0e9d9a
      InstanceType: t2.micro

