#!/bin/bash

# Update the package list
sudo apt-get update -y

# Install MySQL Server
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server

# Start MySQL Service
sudo service mysql start

# Optional: Secure MySQL Installation
sudo mysql_secure_installation <<EOF

y 
Chandan@12345
Chandan@12345
y
y
y
y
EOF

#  This scrpit will install and lanch the mysql server 

sudo mysql -u root -p'Chandan@12345' <<MYSQL_SCRIPT
CREATE DATABASE database; 
CREATE USER 'user1'@'10.0.2.20' IDENTIFIED BY 'Chandan@12345';
GRANT ALL PRIVILEGES ON your_database.* TO 'user1'@'10.0.2.20';
FLUSH PRIVILEGES;
EXIT;
MYSQL_SCRIPT 

# to enable the comminication we need add address in mysqld.cnf file 
sudo sed -i 's/bind-address\s*=\s*127.0.0.1/bind-address = 10.0.2.20/' /etc/mysql/mysql.conf.d/mysqld.cnf 
# to get changes reflect restart mysql
sudo service mysql restart
