Resources:
Mini-Network-VPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/24
    EnableDnsSupport: 'true'
    EnableDnsHostnames: 'true'
    Tags:
     - Key: Name
       Value: Mini-Network



  Ec2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: chandan  
      ImageId: ami-0287a05f0ef0e9d9a
      InstanceType: t2.micro
      AvailabilityZone: ap-south-1b
      Tags:
        - Key: Name
          Value: Backend-Appication
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y 
          sudo apt install nginx -y
          sudo service nginx start
      NetworkInterfaces:
        - GroupSet:
            - !Ref InstanceSecurityGroup
          #AssociatePublicIpAddress: false
          SubnetId: !Ref PrivateSubnet
          DeviceIndex: 0
          PrivateIpAddress: '10.0.2.10'
